name: 'pollution-tracker'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.1
  - altair=5.2.0
  - vega_datasets=0.9.0
  - altair_data_server=0.4.1
  - matplotlib=3.8.3
  - gunicorn==21.2
  - pip
  - pip:
    - dash==2.16.1
    - dash-leaflet==1.0.15
    - dash-extensions==1.0.14
    - dash_bootstrap_components==1.5.0
    - plotly==5.20.0